spring:
  http:
    multipart:
      max-file-size: 1000MB
  data:
    mongodb:
      database: oss
  cache:
      ehcache:
        config: ehcache.xml
  profiles:
    active: log
server:
  session:
    timeout: -1
  port: 80
endpoints:
  actuator:
    enabled: true
